"""
Data Transfer Objects (DTOs) for Hue API v2.
This package contains Pydantic models for all API requests and responses.
"""

# Common DTOs
from .common_dto import (
    ApiErrorDTO,
    ApiResponseDTO,
    ButtonEventDTO,
    BridgeConfigDTO,
    BridgeResponseDTO,
    DevicePowerDTO,
    EntertainmentChannelDTO,
    EntertainmentConfigurationDTO,
    ErrorResponseDTO,
    EventDTO,
    HomekitDTO,
    LightLevelSensorDTO,
    MotionSensorDTO,
    ResourceCollectionDTO,
    ResourceDTO,
    ResourceIdentifierDTO,
    ResourceListResponseDTO,
    SingleResourceResponseDTO,
    TemperatureSensorDTO,
    ZigbeeConnectivityDTO,
)

# Light DTOs
from .light_dto import (
    AlertDTO as LightAlertDTO,
    ColorDTO as LightColorDTO,
    ColorTemperatureDTO as LightColorTemperatureDTO,
    ColorTemperatureDeltaDTO,
    ContentConfigurationDTO,
    DimmingDTO as LightDimmingDTO,
    DimmingDeltaDTO,
    DynamicsDTO as LightDynamicsDTO,
    EffectActionDTO,
    EffectsDTO as LightEffectsDTO,
    EffectStatusDTO,
    EffectsV2DTO,
    GamutDTO,
    GradientDTO as LightGradientDTO,
    GradientPointDTO as LightGradientPointDTO,
    LightIdentifyDTO,
    LightListResponseDTO,
    LightResponseDTO,
    LightUpdateDTO,
    LightUpdateResponseDTO,
    MetadataDTO as LightMetadataDTO,
    MirekSchemaDTO,
    OrderDTO,
    OrientationDTO,
    PowerupColorDTO,
    PowerupDimmingDTO,
    PowerupDTO,
    PowerupOnDTO,
    ProductDataDTO,
    SignalingDTO as LightSignalingDTO,
    TimedEffectsDTO,
    XyDTO,
)

# Room DTOs
from .room_dto import (
    RoomCreateDTO,
    RoomCreateResponseDTO,
    RoomDeleteResponseDTO,
    RoomListResponseDTO,
    RoomResponseDTO,
    RoomUpdateDTO,
    RoomUpdateResponseDTO,
)

# Scene DTOs
from .scene_dto import (
    ActionDTO as SceneActionDTO,
    DimmingDTO as SceneDimmingDTO,
    PaletteColorDTO,
    PaletteColorTemperatureDTO,
    PaletteDTO,
    SceneCreateDTO,
    SceneCreateResponseDTO,
    SceneDeleteResponseDTO,
    SceneListResponseDTO,
    SceneRecallDTO,
    SceneResponseDTO,
    SceneStatusDTO,
    SceneUpdateDTO,
    SceneUpdateResponseDTO,
)

# Device DTOs
from .device_dto import (
    DeviceIdentifyDTO,
    DeviceListResponseDTO,
    DeviceDeleteResponseDTO,
    DeviceResponseDTO,
    DeviceUpdateDTO,
    DeviceUpdateResponseDTO,
    UserTestDTO,
)

# Grouped Light DTOs
from .grouped_light_dto import (
    GroupedLightIdentifyDTO,
    GroupedLightListResponseDTO,
    GroupedLightResponseDTO,
    GroupedLightUpdateDTO,
    GroupedLightUpdateResponseDTO,
)

__all__ = [
    # Common
    "ApiErrorDTO",
    "ApiResponseDTO",
    "ButtonEventDTO",
    "BridgeConfigDTO",
    "BridgeResponseDTO",
    "DevicePowerDTO",
    "EntertainmentChannelDTO",
    "EntertainmentConfigurationDTO",
    "ErrorResponseDTO",
    "EventDTO",
    "HomekitDTO",
    "LightLevelSensorDTO",
    "MotionSensorDTO",
    "ResourceCollectionDTO",
    "ResourceDTO",
    "ResourceIdentifierDTO",
    "ResourceListResponseDTO",
    "SingleResourceResponseDTO",
    "TemperatureSensorDTO",
    "ZigbeeConnectivityDTO",
    # Light
    "LightAlertDTO",
    "LightColorDTO",
    "LightColorTemperatureDTO",
    "ColorTemperatureDeltaDTO",
    "ContentConfigurationDTO",
    "LightDimmingDTO",
    "DimmingDeltaDTO",
    "LightDynamicsDTO",
    "EffectActionDTO",
    "LightEffectsDTO",
    "EffectStatusDTO",
    "EffectsV2DTO",
    "GamutDTO",
    "LightGradientDTO",
    "LightGradientPointDTO",
    "LightIdentifyDTO",
    "LightListResponseDTO",
    "LightResponseDTO",
    "LightUpdateDTO",
    "LightUpdateResponseDTO",
    "LightMetadataDTO",
    "MirekSchemaDTO",
    "OrderDTO",
    "OrientationDTO",
    "PowerupColorDTO",
    "PowerupDimmingDTO",
    "PowerupDTO",
    "PowerupOnDTO",
    "ProductDataDTO",
    "LightSignalingDTO",
    "TimedEffectsDTO",
    "XyDTO",
    # Room
    "RoomCreateDTO",
    "RoomCreateResponseDTO",
    "RoomDeleteResponseDTO",
    "RoomListResponseDTO",
    "RoomResponseDTO",
    "RoomUpdateDTO",
    "RoomUpdateResponseDTO",
    # Scene
    "SceneActionDTO",
    "SceneDimmingDTO",
    "PaletteColorDTO",
    "PaletteColorTemperatureDTO",
    "PaletteDTO",
    "SceneCreateDTO",
    "SceneCreateResponseDTO",
    "SceneDeleteResponseDTO",
    "SceneListResponseDTO",
    "SceneRecallDTO",
    "SceneResponseDTO",
    "SceneStatusDTO",
    "SceneUpdateDTO",
    "SceneUpdateResponseDTO",
    # Device
    "DeviceIdentifyDTO",
    "DeviceListResponseDTO",
    "DeviceDeleteResponseDTO",
    "DeviceResponseDTO",
    "DeviceUpdateDTO",
    "DeviceUpdateResponseDTO",
    "UserTestDTO",
    # Grouped Light
    "GroupedLightIdentifyDTO",
    "GroupedLightListResponseDTO",
    "GroupedLightResponseDTO",
    "GroupedLightUpdateDTO",
    "GroupedLightUpdateResponseDTO",
]
